### ISSUE TITLE
Update Makefile to dynamically build using the golang build image.

### ISSUE THREAD

**Issue by jayunit100** [blackducksoftware/perceivers#13]
We want to do stateless builds, via the 

``` 
sudo docker run --rm -e CGO_ENABLED=0 -e GOOS=linux -e GOARCH=amd64 -v "$PWD":/go/src/github.com/blackducksoftware/perceivers -w /go/src/github.com/blackducksoftware/perceivers golang go build ./image/cmd/image-perceiver.go
```
trick which @msenmurugan has adopted inside of the perceptor builds.

@rrati has suggested a good way to do this is to integrate it w/ make...

Once that integration is done, lets go update our bots to use make for perceivers rather then using the `...golang build` image.

**Comment by rrati** [comment]
Done
