### ISSUE TITLE
Perceiver Openshift POD: Segmentation Violation and POD goes into a CrashLoopBackoff

### ISSUE THREAD

**Issue by sheppduck** [blackducksoftware/perceivers#15]
System:
https://ec2-18-218-24-122.us-east-2.compute.amazonaws.com:8443/console
Login:
Secret, ask me . :)

Nothing of note in the perceiver log leading up to this problem, but then again this was the 212th restart so whatever the underlying issue is remains and just shits out faster than say the very first instance of this problem.
============================================
From the Log, last handful of lines:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xdf0d48]
goroutine 20 [running]:
github.com/blackducksoftware/perceivers/pod/pkg/annotator.(*PodAnnotator).createImageAnnotationsFromImageScanResults(...)
	/Users/smanikantan/work/src/github.com/blackducksoftware/perceivers/pod/pkg/annotator/pod_annotator.go:181
github.com/blackducksoftware/perceivers/pod/pkg/annotator.(*PodAnnotator).setAnnotationsOnPod(0xc420522660, 0xc420232590, 0xe, 0xc420232550, 0x6, 0xc420a8fe88, 0xc420852000, 0x95, 0xd3, 0x0, ...)
	/Users/smanikantan/work/src/github.com/blackducksoftware/perceivers/pod/pkg/annotator/pod_annotator.go:134 +0x5a8
github.com/blackducksoftware/perceivers/pod/pkg/annotator.(*PodAnnotator).Run(0xc420522660, 0x6fc23ac00, 0xc4200604e0)
	/Users/smanikantan/work/src/github.com/blackducksoftware/perceivers/pod/pkg/annotator/pod_annotator.go:91 +0x6f8
created by github.com/blackducksoftware/perceivers/pod/cmd/app.(*PodPerceiver).Run
	/Users/smanikantan/work/src/github.com/blackducksoftware/perceivers/pod/cmd/app/podperceiver.go:77 +0xc6

**Comment by sheppduck** [comment]
[issue_15.txt](https://github.com/blackducksoftware/perceivers/files/1745520/issue_15.txt)

**Comment by rrati** [comment]
@sheppduck Try latest code.  This should be fixed already

**Comment by rrati** [comment]
@sheppduck I believe this is already fixed.  Closing.  If you run into this again please re-open.
