### ISSUE TITLE
Unable to get image : needs log statement.

### ISSUE THREAD

**Issue by jayunit100** [blackducksoftware/perceivers#32]
We see rare instances of 'unable to get image' in perceivers.  Presumealby this happens if an image is deleted after perceiver is told it needs to be annotated.

<img width="1054" alt="screen shot 2018-03-21 at 9 35 53 am" src="https://user-images.githubusercontent.com/826111/37712800-5f7dc7ae-2ceb-11e8-8baa-f2df77a79d4e.png">

Lets log those image names (better yet if multiple maybe consider aggregating them into a set over time and reporting so users can see how many unannotatablbe images are in the system)

**Comment by rrati** [comment]
This is likely because there is no differentiation between openshift images and external images.  For openshift, a not found image is likely an external image and not one openshift knows about.  Looks more like a problem with the metrics than an actual problem.
