### ISSUE TITLE
"panic" message in image and pod-perceivers

### ISSUE THREAD

**Issue by jlin963** [blackducksoftware/perceivers#41]
I tried to spin up a Minishift cluster today and both image-perceiver and pod-perceiver have a status of "Crash Loop Back-off". Looking at the logs, both of them are printing "panic" messages.

Image perceiver:

> panic: a previously registered descriptor with the same fully-qualified name as Desc{fqName: "perceptor_image_perceiver_annotations", help: "images annotated", constLabels: {}, variableLabels: [annotator images_annotated]} has different label names or a different help string

Pod perceiver:

> panic: a previously registered descriptor with the same fully-qualified name as Desc{fqName: "perceptor_pod_perceiver_annotations", help: "pods annotated", constLabels: {}, variableLabels: [annotator pods_annotated]} has different label names or a different help string

fyi, I'm using a Hub that still has scan results from last week (when I was also using Minishift, although I delete the Minishift instance I'm using at the end of each workday). I think minishift start also assigned the same IP address as it did last Friday, despite the minishift delete. 

[image-perceiver.txt](https://github.com/blackducksoftware/perceivers/files/1848977/image-perceiver.txt)
[pod-perceiver.txt](https://github.com/blackducksoftware/perceivers/files/1848978/pod-perceiver.txt)

**Comment by mattfenwick** [comment]
@jlin963 this should be addressed by #43
