### ISSUE TITLE
Long image names:  unable to update annotations/labels for pod... must be no more than 63 characters

### ISSUE THREAD

**Issue by sheppduck** [blackducksoftware/perceivers#61]
The perceiver can come across images with long names and the following error is throw in the log:
time="2018-04-18T17:21:19Z" level=error msg="unable to update annotations/labels for pod openshift-template-service-broker:apiserver-lz5tb: Pod \"apiserver-lz5tb\" is invalid: metadata.labels: Invalid value: \"registry.access.redhat.com.openshift3.ose-template-service-broker\": must be no more than 63 characters"

Looks like we should maybe be ignoring the registry name, if possible?

**Comment by jayunit100** [comment]
Just do the first 63 characters and be done with it.

**Comment by jayunit100** [comment]
@msenmurugan has a simple fix for this, should we merge it?

**Comment by rrati** [comment]
@jayunit100 No, the fix doesn't really fix things.  It can result in meaningless values.  Please just hold off until we reproduce for the proper fix

**Comment by rrati** [comment]
closed via #62
